### ISSUE TITLE
Unsafe Eval on Linux

### ISSUE THREAD

**Issue by WingofaGriffin** [santolucito/liveprogramming#2]
Currently looking for a solution, placing this here for documentation.

**Atom**: 1.36.0 x64
**Electron**: 4.1.4
**OS**: linux 5.0.9-arch1-1-ARCH
**Thrown From**: [live-programming1](https://github.com/atom/live-programming1) package 0.0.0

### Stack Trace

Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

```
At /home/griffin/School/liveprogramming/lib/javascript/sygus_converter.js:50

EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

    at getInputOutputType (/home/griffin/School/liveprogramming/lib/javascript/sygus_converter.js:50:79)
    at genFunctionSynth (/home/griffin/School/liveprogramming/lib/javascript/sygus_converter.js:90:15)
    at codeToSygus (/home/griffin/School/liveprogramming/lib/javascript/sygus_converter.js:239:20)
    at pbeRepair (/home/griffin/School/liveprogramming/lib/javascript/eval_pbe_helpers.js:31:26)
    at Object.repair (/home/griffin/School/liveprogramming/lib/javascript/eval_pbe_helpers.js:50:50)
    at updateCodeEval (/home/griffin/School/liveprogramming/lib/general/eval_pbe_helpers.js:18:25)
    at updateCodeEvalJS (/home/griffin/School/liveprogramming/lib/javascript/eval_pbe_helpers.js:50:10)
    at updateCodeEvalAtom (/home/griffin/School/liveprogramming/lib/live-programming1.js:17:13)
    at Function.simpleDispatch (/usr/lib/atom/node_modules/event-kit/dist/emitter.js:64:14)
    at Emitter.emit (/usr/lib/atom/node_modules/event-kit/dist/emitter.js:257:28)
    at Workspace.didChangeActivePaneItemOnPaneContainer (/usr/lib/atom/src/workspace.js:429:20)
    at WorkspaceCenter.paneContainer.onDidChangeActivePaneItem (/usr/lib/atom/src/workspace-center.js:17:14)
    at Function.simpleDispatch (/usr/lib/atom/node_modules/event-kit/dist/emitter.js:64:14)
    at Emitter.emit (/usr/lib/atom/node_modules/event-kit/dist/emitter.js:257:28)
    at PaneContainer.didChangeActiveItemOnPane (/usr/lib/atom/src/pane-container.js:281:20)
    at PaneContainer.didActivatePane (/usr/lib/atom/src/pane-container.js:259:12)
    at Pane.activate (/usr/lib/atom/src/pane.js:1014:40)
    at Pane.focus (/usr/lib/atom/src/pane.js:397:17)
    at HTMLElement.handleFocus (/usr/lib/atom/src/pane-element.js:41:20)
```

### Commands

```
     -0:12.8.0 live-programming1:toggle (input.hidden-input)
  8x -0:10.9.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
live-programming1 0.0.0 
```

**Comment by WingofaGriffin** [comment]
Seems to be resolved. Still has some other bugs such but is functioning
